// Plant Catalog - Extended database for the Plant Library page
// Rich metadata for filtering, seasonal info, companion plants, etc.

export type PlantType = "tree" | "shrub" | "groundcover" | "grass" | "perennial" | "succulent";
export type WaterNeeds = "none" | "low" | "moderate" | "high";
export type MaintenanceLevel = "none" | "low" | "moderate" | "high";
export type GrowthRate = "slow" | "moderate" | "fast";

export interface SeasonInfo {
  foliage: string;
  interest: string;
}

export interface PlantCatalogEntry {
  id: string;
  name: string;
  scientific: string;
  family: string;
  type: PlantType;
  nativeCalifornia: boolean;
  deerResistant: boolean;
  fireResistant: boolean;
  form: string;
  matureHeight: [number, number];
  matureWidth: [number, number];
  growthRate: GrowthRate;
  /** Fraction of mature size at key years (0-1) */
  growthParam: { 1: number; 5: number; 10: number; 20: number; 30: number };
  sunlight: string[];
  waterNeeds: WaterNeeds;
  soilTypes: string[];
  windTolerance: "low" | "moderate" | "high";
  heatTolerance: "low" | "moderate" | "high";
  situations: string[];
  goals: string[];
  companionPlants: string[];
  maintenanceLevel: MaintenanceLevel;
  pruningNeeds: string;
  flowerColor: string[];
  flowerSeason: string[];
  foliageColor: string[];
  fallColor: string | null;
  seasons: {
    spring: SeasonInfo;
    summer: SeasonInfo;
    fall: SeasonInfo;
    winter: SeasonInfo;
  };
  why: string;
  color: string;
  estimatedCostRange: [number, number];
  usdaZones: string[];
}

/** Interpolate growth fraction at a given year */
export function getGrowthFraction(plant: PlantCatalogEntry, year: number): number {
  const pts = plant.growthParam;
  const keys = [1, 5, 10, 20, 30] as const;
  if (year <= 1) return pts[1];
  if (year >= 30) return pts[30];
  for (let i = 0; i < keys.length - 1; i++) {
    const k0 = keys[i], k1 = keys[i + 1];
    if (year >= k0 && year <= k1) {
      const frac = (year - k0) / (k1 - k0);
      return pts[k0] + (pts[k1] - pts[k0]) * frac;
    }
  }
  return pts[30];
}

/** Estimated height in feet at a given year */
export function getHeightAtYear(plant: PlantCatalogEntry, year: number): number {
  const t = getGrowthFraction(plant, year);
  const mid = (plant.matureHeight[0] + plant.matureHeight[1]) / 2;
  return Math.round(mid * t * 10) / 10;
}

export const PLANT_CATALOG: PlantCatalogEntry[] = [
  {
    id: "coast-live-oak",
    name: "Coast Live Oak",
    scientific: "Quercus agrifolia",
    family: "Fagaceae",
    type: "tree",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Broad spreading canopy with gnarled branches",
    matureHeight: [30, 70],
    matureWidth: [30, 80],
    growthRate: "slow",
    growthParam: { 1: 0.04, 5: 0.15, 10: 0.30, 20: 0.60, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam", "Rocky"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Wildlife Habitat", "Large Property", "Meadow"],
    goals: ["Shade", "Wildlife", "Privacy", "Windbreak", "Statement Tree"],
    companionPlants: ["toyon", "coffeeberry", "western-redbud", "creeping-sage"],
    maintenanceLevel: "low",
    pruningNeeds: "Minimal — remove deadwood every 3-5 years",
    flowerColor: ["Yellow-Green"],
    flowerSeason: ["Spring"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Rich dark green new growth", interest: "Catkins and fresh leaves" },
      summer: { foliage: "Dense dark green canopy", interest: "Deep shade and acorn development" },
      fall: { foliage: "Evergreen, holds leaves", interest: "Acorns ripen, attracting wildlife" },
      winter: { foliage: "Evergreen", interest: "Structure and wildlife shelter" }
    },
    why: "California's iconic native oak — centuries of character, drought-proof once established",
    color: "#2F4F2F",
    estimatedCostRange: [150, 500],
    usdaZones: ["9a", "9b", "10a", "10b"]
  },
  {
    id: "toyon",
    name: "Toyon",
    scientific: "Heteromeles arbutifolia",
    family: "Rosaceae",
    type: "shrub",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: true,
    form: "Multi-stemmed upright shrub or small tree",
    matureHeight: [6, 15],
    matureWidth: [5, 12],
    growthRate: "moderate",
    growthParam: { 1: 0.10, 5: 0.35, 10: 0.65, 20: 0.90, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Wildlife Habitat", "Screening", "Fire-Prone Area"],
    goals: ["Wildlife", "Privacy", "Erosion Control", "Winter Interest"],
    companionPlants: ["coast-live-oak", "coffeeberry", "western-redbud", "manzanita"],
    maintenanceLevel: "low",
    pruningNeeds: "Light shaping after fruiting if desired",
    flowerColor: ["White"],
    flowerSeason: ["Summer"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Glossy dark green", interest: "White flower clusters begin" },
      summer: { foliage: "Rich green", interest: "Peak bloom, fragrant white flowers" },
      fall: { foliage: "Evergreen", interest: "Red berries ripen — Hollywood's Christmas plant" },
      winter: { foliage: "Evergreen", interest: "Brilliant red berries attract birds" }
    },
    why: "Winter-red berries and fire resistance make it indispensable in California gardens",
    color: "#8B1A1A",
    estimatedCostRange: [25, 80],
    usdaZones: ["7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "coffeeberry",
    name: "California Coffeeberry",
    scientific: "Frangula californica",
    family: "Rhamnaceae",
    type: "shrub",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: true,
    form: "Rounded multi-stemmed shrub",
    matureHeight: [4, 10],
    matureWidth: [4, 8],
    growthRate: "moderate",
    growthParam: { 1: 0.12, 5: 0.40, 10: 0.70, 20: 0.90, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade", "Full Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Rocky", "Sandy"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Wildlife Habitat", "Understory", "Screening"],
    goals: ["Wildlife", "Privacy", "Erosion Control", "Shade Tolerant"],
    companionPlants: ["coast-live-oak", "toyon", "manzanita", "creeping-sage"],
    maintenanceLevel: "low",
    pruningNeeds: "Minimal — remove crossing branches as needed",
    flowerColor: ["Greenish-White"],
    flowerSeason: ["Spring", "Summer"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Glossy dark green", interest: "Small flower clusters" },
      summer: { foliage: "Green", interest: "Berries transition from green to red to black" },
      fall: { foliage: "Evergreen", interest: "Multi-colored berries attract birds" },
      winter: { foliage: "Evergreen", interest: "Structure and bird food" }
    },
    why: "Multi-season berry show and shade tolerance fill gaps other natives can't",
    color: "#4A6741",
    estimatedCostRange: [20, 65],
    usdaZones: ["7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "western-redbud",
    name: "Western Redbud",
    scientific: "Cercis occidentalis",
    family: "Fabaceae",
    type: "shrub",
    nativeCalifornia: true,
    deerResistant: false,
    fireResistant: false,
    form: "Multi-stemmed large shrub or small tree",
    matureHeight: [10, 18],
    matureWidth: [8, 15],
    growthRate: "moderate",
    growthParam: { 1: 0.10, 5: 0.38, 10: 0.65, 20: 0.88, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Rocky", "Clay", "Loam"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Slope", "Wildlife Habitat", "Dry Garden", "Large Property"],
    goals: ["Spring Color", "Wildlife", "Statement Tree", "Four-Season Interest"],
    companionPlants: ["coast-live-oak", "toyon", "manzanita", "blue-wild-rye"],
    maintenanceLevel: "low",
    pruningNeeds: "Remove deadwood after bloom; occasional shaping",
    flowerColor: ["Magenta", "Pink"],
    flowerSeason: ["Spring"],
    foliageColor: ["Blue-Green"],
    fallColor: "Yellow",
    seasons: {
      spring: { foliage: "Emerging blue-green heart leaves", interest: "Spectacular magenta bloom before leaves" },
      summer: { foliage: "Blue-green heart-shaped leaves", interest: "Flat seed pods add texture" },
      fall: { foliage: "Yellow-gold", interest: "Brilliant fall color and seed pods" },
      winter: { foliage: "Bare", interest: "Sculptural branch structure" }
    },
    why: "Best spring show of any California native — magenta flowers coat bare branches",
    color: "#C62391",
    estimatedCostRange: [30, 90],
    usdaZones: ["6b", "7a", "7b", "8a", "8b", "9a", "9b"]
  },
  {
    id: "manzanita",
    name: "Manzanita",
    scientific: "Arctostaphylos spp.",
    family: "Ericaceae",
    type: "shrub",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Varies by species — mounding to upright",
    matureHeight: [2, 12],
    matureWidth: [3, 12],
    growthRate: "slow",
    growthParam: { 1: 0.08, 5: 0.28, 10: 0.55, 20: 0.82, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Dry Garden", "Wildlife Habitat", "Fire-Prone Area"],
    goals: ["Erosion Control", "Wildlife", "Winter Interest", "Low Water"],
    companionPlants: ["toyon", "coffeeberry", "creeping-sage", "blue-wild-rye"],
    maintenanceLevel: "none",
    pruningNeeds: "Avoid heavy pruning — remove dead wood only",
    flowerColor: ["White", "Pink"],
    flowerSeason: ["Winter", "Spring"],
    foliageColor: ["Blue-Green", "Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Leathery gray-green", interest: "Urn-shaped flowers attract hummingbirds" },
      summer: { foliage: "Gray-green", interest: "Red-brown berries forming" },
      fall: { foliage: "Evergreen", interest: "Berries attract wildlife" },
      winter: { foliage: "Evergreen", interest: "Flowers open — stunning red bark year-round" }
    },
    why: "Polished red bark and zero summer water needs are unmatched in California landscapes",
    color: "#8B3A3A",
    estimatedCostRange: [20, 75],
    usdaZones: ["7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "blue-wild-rye",
    name: "Blue Wild Rye",
    scientific: "Elymus glaucus",
    family: "Poaceae",
    type: "grass",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Upright clumping grass",
    matureHeight: [2, 4],
    matureWidth: [1, 2],
    growthRate: "fast",
    growthParam: { 1: 0.40, 5: 0.80, 10: 0.95, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam", "Rocky"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Meadow", "Understory", "Dry Garden"],
    goals: ["Erosion Control", "Low Water", "Naturalistic", "Wildlife"],
    companionPlants: ["western-redbud", "coffeeberry", "creeping-sage", "yarrow"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut back to 4 inches in late summer or early spring",
    flowerColor: ["Tan", "Wheat"],
    flowerSeason: ["Summer"],
    foliageColor: ["Blue-Green"],
    fallColor: "Tan",
    seasons: {
      spring: { foliage: "Blue-green fresh growth", interest: "Quick spring green-up" },
      summer: { foliage: "Blue-green with seed heads", interest: "Wheat-colored seed stalks wave in breeze" },
      fall: { foliage: "Tan and straw", interest: "Winter bird food in seed heads" },
      winter: { foliage: "Semi-evergreen to dormant", interest: "Structural seed heads" }
    },
    why: "Native grass meadows start here — tough, beautiful, and bird-friendly",
    color: "#6B8E6B",
    estimatedCostRange: [8, 25],
    usdaZones: ["5a", "6a", "7a", "8a", "9a", "9b"]
  },
  {
    id: "creeping-sage",
    name: "Creeping Sage",
    scientific: "Salvia sonomensis",
    family: "Lamiaceae",
    type: "groundcover",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Low mat-forming groundcover",
    matureHeight: [0.5, 1.5],
    matureWidth: [4, 8],
    growthRate: "moderate",
    growthParam: { 1: 0.20, 5: 0.60, 10: 0.88, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Dry Garden", "Under Oaks", "Fire-Prone Area"],
    goals: ["Erosion Control", "Low Water", "Ground Cover", "Weed Suppression"],
    companionPlants: ["manzanita", "coffeeberry", "blue-wild-rye", "toyon"],
    maintenanceLevel: "none",
    pruningNeeds: "Light shear after bloom to keep tidy",
    flowerColor: ["Lavender", "Purple"],
    flowerSeason: ["Spring"],
    foliageColor: ["Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Silvery-gray aromatic", interest: "Lavender flower spikes" },
      summer: { foliage: "Gray-green", interest: "Evergreen mat holds slope" },
      fall: { foliage: "Evergreen", interest: "Fragrant foliage in fall rains" },
      winter: { foliage: "Evergreen", interest: "Green mat in dormant garden" }
    },
    why: "Covers difficult slopes under oaks with zero summer water — smells amazing too",
    color: "#8B82BE",
    estimatedCostRange: [10, 30],
    usdaZones: ["7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "japanese-maple",
    name: "Japanese Maple",
    scientific: "Acer palmatum",
    family: "Sapindaceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: false,
    fireResistant: false,
    form: "Layered multi-stemmed tree — weeping, upright, or mounding by cultivar",
    matureHeight: [6, 25],
    matureWidth: [6, 20],
    growthRate: "slow",
    growthParam: { 1: 0.06, 5: 0.22, 10: 0.45, 20: 0.78, 30: 1.0 },
    sunlight: ["Partial Shade", "Filtered Sun"],
    waterNeeds: "moderate",
    soilTypes: ["Well-drained", "Loam", "Amended"],
    windTolerance: "low",
    heatTolerance: "low",
    situations: ["Patio", "Courtyard", "Understory", "Japanese Garden"],
    goals: ["Statement Tree", "Four-Season Interest", "Fall Color", "Small Space"],
    companionPlants: ["heavenly-bamboo", "agapanthus", "indian-hawthorn", "festuca"],
    maintenanceLevel: "low",
    pruningNeeds: "Minimal — remove crossing branches in winter",
    flowerColor: ["Red", "Purple"],
    flowerSeason: ["Spring"],
    foliageColor: ["Red", "Purple", "Green", "Variegated"],
    fallColor: "Crimson",
    seasons: {
      spring: { foliage: "Delicate emerging leaves, often red-tipped", interest: "Tiny ornamental flowers" },
      summer: { foliage: "Lush layered canopy", interest: "Winged samaras helicopter seeds" },
      fall: { foliage: "Crimson, orange, gold", interest: "Best fall color of any small tree" },
      winter: { foliage: "Bare", interest: "Graceful sculptural branch architecture" }
    },
    why: "Unrivaled four-season beauty in a compact form — a living sculpture",
    color: "#C0392B",
    estimatedCostRange: [60, 400],
    usdaZones: ["5b", "6a", "6b", "7a", "7b", "8a", "8b"]
  },
  {
    id: "italian-cypress",
    name: "Italian Cypress",
    scientific: "Cupressus sempervirens",
    family: "Cupressaceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Narrow columnar exclamation point",
    matureHeight: [40, 70],
    matureWidth: [3, 6],
    growthRate: "moderate",
    growthParam: { 1: 0.05, 5: 0.20, 10: 0.45, 20: 0.78, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Rocky", "Sandy", "Clay"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Driveway", "Entry", "Formal Garden", "Screening"],
    goals: ["Privacy", "Windbreak", "Formal Structure", "Statement Tree"],
    companionPlants: ["lavender", "rosemary", "olive-tree", "chinese-pistache"],
    maintenanceLevel: "low",
    pruningNeeds: "None needed — let it grow naturally",
    flowerColor: ["Yellow-Green"],
    flowerSeason: ["Spring"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Dark green columns", interest: "Small cones developing" },
      summer: { foliage: "Deep green", interest: "Striking vertical silhouette" },
      fall: { foliage: "Evergreen", interest: "Bronze-tipped new growth" },
      winter: { foliage: "Evergreen", interest: "Bold vertical structure in dormant garden" }
    },
    why: "Instant Mediterranean drama — pairs perfectly with stone, olive trees, and lavender",
    color: "#2D5A27",
    estimatedCostRange: [40, 200],
    usdaZones: ["7b", "8a", "8b", "9a", "9b", "10a", "10b", "11a"]
  },
  {
    id: "lavender",
    name: "Lavender",
    scientific: "Lavandula spp.",
    family: "Lamiaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Mounding aromatic subshrub",
    matureHeight: [1.5, 4],
    matureWidth: [2, 5],
    growthRate: "moderate",
    growthParam: { 1: 0.25, 5: 0.65, 10: 0.88, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Border", "Pathway", "Dry Garden", "Pollinator Garden"],
    goals: ["Pollinator Habitat", "Fragrance", "Low Water", "Edging"],
    companionPlants: ["rosemary", "italian-cypress", "olive-tree", "salvia-greggii"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut back by 1/3 after bloom; hard renewal every 3-4 years",
    flowerColor: ["Purple", "Blue", "White", "Pink"],
    flowerSeason: ["Spring", "Summer"],
    foliageColor: ["Silver-Gray"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Silver-gray aromatic mound", interest: "Purple flower wands begin" },
      summer: { foliage: "Silver-gray", interest: "Peak fragrant bloom, bees everywhere" },
      fall: { foliage: "Silver-gray", interest: "Second flush of bloom" },
      winter: { foliage: "Silver-gray evergreen", interest: "Structure in winter garden" }
    },
    why: "Fragrance, pollinators, and silver color make it the perfect dry-garden anchor",
    color: "#9B59B6",
    estimatedCostRange: [12, 45],
    usdaZones: ["5a", "6a", "7a", "8a", "9a", "9b", "10a"]
  },
  {
    id: "chinese-pistache",
    name: "Chinese Pistache",
    scientific: "Pistacia chinensis",
    family: "Anacardiaceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Rounded shade tree with vase habit in youth",
    matureHeight: [25, 40],
    matureWidth: [25, 35],
    growthRate: "moderate",
    growthParam: { 1: 0.08, 5: 0.28, 10: 0.55, 20: 0.82, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam", "Sandy"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Street Tree", "Large Property", "Lawn", "Parking Area"],
    goals: ["Shade", "Fall Color", "Low Water", "Street Tree"],
    companionPlants: ["italian-cypress", "lavender", "agapanthus", "rosemary"],
    maintenanceLevel: "low",
    pruningNeeds: "Train young tree for structure; minimal once established",
    flowerColor: ["Red", "Green"],
    flowerSeason: ["Spring"],
    foliageColor: ["Medium Green"],
    fallColor: "Orange-Red",
    seasons: {
      spring: { foliage: "Fresh medium-green pinnate leaves", interest: "Small red flower clusters" },
      summer: { foliage: "Dense green canopy", interest: "Deep cooling shade" },
      fall: { foliage: "Orange, red, and gold", interest: "Best fall color of drought-tolerant trees" },
      winter: { foliage: "Bare", interest: "Attractive gray bark and branch structure" }
    },
    why: "Best fall color of any drought-tolerant shade tree in California — reliable year after year",
    color: "#E67E22",
    estimatedCostRange: [60, 250],
    usdaZones: ["6b", "7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "crape-myrtle",
    name: "Crape Myrtle",
    scientific: "Lagerstroemia indica",
    family: "Lythraceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Multi-stemmed vase-shaped tree or shrub",
    matureHeight: [8, 30],
    matureWidth: [8, 20],
    growthRate: "fast",
    growthParam: { 1: 0.12, 5: 0.42, 10: 0.72, 20: 0.92, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Patio", "Street Tree", "Lawn", "Border"],
    goals: ["Summer Color", "Fall Color", "Statement Tree", "Low Water"],
    companionPlants: ["agapanthus", "lavender", "rosemary", "salvia-greggii"],
    maintenanceLevel: "low",
    pruningNeeds: "Never top ('crape murder'); remove suckers and crossing branches",
    flowerColor: ["Pink", "Red", "White", "Purple", "Lavender"],
    flowerSeason: ["Summer", "Fall"],
    foliageColor: ["Medium Green"],
    fallColor: "Orange-Red",
    seasons: {
      spring: { foliage: "Fresh green emerging leaves, often reddish-bronze", interest: "Attractive new growth" },
      summer: { foliage: "Medium green", interest: "Spectacular months-long bloom in heat" },
      fall: { foliage: "Orange-red", interest: "Fall color plus late flowers" },
      winter: { foliage: "Bare", interest: "Exfoliating cinnamon-tan bark is stunning" }
    },
    why: "Blooms for 90+ days in summer heat when almost nothing else will",
    color: "#E91E8C",
    estimatedCostRange: [35, 200],
    usdaZones: ["6b", "7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "olive-tree",
    name: "Olive Tree",
    scientific: "Olea europaea",
    family: "Oleaceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Gnarled multi-stemmed Mediterranean canopy",
    matureHeight: [20, 30],
    matureWidth: [20, 30],
    growthRate: "slow",
    growthParam: { 1: 0.04, 5: 0.18, 10: 0.38, 20: 0.70, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Rocky", "Sandy", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Patio", "Formal Garden", "Mediterranean Garden", "Driveway"],
    goals: ["Statement Tree", "Low Water", "Formal Structure", "Edible"],
    companionPlants: ["italian-cypress", "lavender", "rosemary", "agave"],
    maintenanceLevel: "low",
    pruningNeeds: "Annual light shaping; fruit variety requires more management",
    flowerColor: ["Cream", "White"],
    flowerSeason: ["Spring"],
    foliageColor: ["Silver-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Silver-green billowing", interest: "Tiny fragrant cream flowers" },
      summer: { foliage: "Silver-green", interest: "Olives forming" },
      fall: { foliage: "Evergreen silver-green", interest: "Black or green olives ripen" },
      winter: { foliage: "Evergreen", interest: "Gorgeous gnarled silver silhouette" }
    },
    why: "Thousand-year presence in a pot or grove — the ultimate Mediterranean anchor",
    color: "#8E9B6B",
    estimatedCostRange: [100, 800],
    usdaZones: ["8a", "8b", "9a", "9b", "10a", "10b", "11a"]
  },
  {
    id: "rosemary",
    name: "Rosemary",
    scientific: "Salvia rosmarinus",
    family: "Lamiaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Upright or prostrate aromatic evergreen",
    matureHeight: [1, 6],
    matureWidth: [2, 6],
    growthRate: "moderate",
    growthParam: { 1: 0.22, 5: 0.60, 10: 0.85, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Border", "Kitchen Garden", "Dry Garden", "Slope"],
    goals: ["Fragrance", "Edible", "Pollinator Habitat", "Low Water"],
    companionPlants: ["lavender", "olive-tree", "italian-cypress", "salvia-greggii"],
    maintenanceLevel: "none",
    pruningNeeds: "Shear after bloom to maintain shape; never cut into old wood",
    flowerColor: ["Blue", "Lavender", "White"],
    flowerSeason: ["Winter", "Spring"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Dark green aromatic needles", interest: "Covered in blue flowers" },
      summer: { foliage: "Dark green", interest: "Fragrant and useful in kitchen" },
      fall: { foliage: "Evergreen", interest: "Second bloom often occurs" },
      winter: { foliage: "Evergreen", interest: "Blooms through winter in mild climates" }
    },
    why: "Zero-water beauty you can cook with — pollinators and chefs both love it",
    color: "#3B6E8C",
    estimatedCostRange: [8, 35],
    usdaZones: ["7a", "7b", "8a", "8b", "9a", "9b", "10a", "10b"]
  },
  {
    id: "agapanthus",
    name: "Agapanthus",
    scientific: "Agapanthus africanus",
    family: "Asparagaceae",
    type: "perennial",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: true,
    form: "Strap-leafed clumping perennial",
    matureHeight: [1.5, 3],
    matureWidth: [2, 3],
    growthRate: "moderate",
    growthParam: { 1: 0.30, 5: 0.70, 10: 0.90, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Border", "Slope", "Driveway", "Pool Area"],
    goals: ["Summer Color", "Low Maintenance", "Erosion Control", "Mass Planting"],
    companionPlants: ["crape-myrtle", "lavender", "chinese-pistache", "indian-hawthorn"],
    maintenanceLevel: "low",
    pruningNeeds: "Remove spent flower stalks; divide clumps every 4-6 years",
    flowerColor: ["Blue", "Purple", "White"],
    flowerSeason: ["Summer"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Lush strap leaves", interest: "Foliage mounding up" },
      summer: { foliage: "Dark green straps", interest: "Tall globe flowers bloom for weeks" },
      fall: { foliage: "Evergreen", interest: "Decorative seed heads" },
      winter: { foliage: "Evergreen", interest: "Structural foliage holds garden" }
    },
    why: "Blue globe flowers on tall stalks are among summer's most elegant performances",
    color: "#4169E1",
    estimatedCostRange: [15, 50],
    usdaZones: ["8a", "8b", "9a", "9b", "10a", "10b"]
  },
  {
    id: "deer-grass",
    name: "Deer Grass",
    scientific: "Muhlenbergia rigens",
    family: "Poaceae",
    type: "grass",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Upright clumping fountain grass",
    matureHeight: [2, 4],
    matureWidth: [3, 5],
    growthRate: "moderate",
    growthParam: { 1: 0.20, 5: 0.55, 10: 0.82, 20: 0.97, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Rocky", "Sandy"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Meadow", "Slope", "Dry Garden", "Border"],
    goals: ["Naturalistic", "Low Water", "Erosion Control", "Wildlife"],
    companionPlants: ["western-redbud", "toyon", "salvia-greggii", "penstemon"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut to 6 inches in late winter before new growth emerges",
    flowerColor: ["Tan", "Purple"],
    flowerSeason: ["Summer", "Fall"],
    foliageColor: ["Green"],
    fallColor: "Tan",
    seasons: {
      spring: { foliage: "Fresh green arching blades", interest: "New growth fountain" },
      summer: { foliage: "Green", interest: "Tall waving flower plumes" },
      fall: { foliage: "Tawny tan", interest: "Seed heads catch light beautifully" },
      winter: { foliage: "Tawny semi-evergreen", interest: "Structural winter form" }
    },
    why: "California's best native ornamental grass — stunning in fall light and bird-friendly",
    color: "#8B8B5A",
    estimatedCostRange: [12, 40],
    usdaZones: ["6a", "7a", "8a", "9a", "9b", "10a"]
  },
  {
    id: "indian-hawthorn",
    name: "Indian Hawthorn",
    scientific: "Rhaphiolepis indica",
    family: "Rosaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: true,
    form: "Compact mounding evergreen shrub",
    matureHeight: [3, 6],
    matureWidth: [4, 6],
    growthRate: "slow",
    growthParam: { 1: 0.10, 5: 0.35, 10: 0.65, 20: 0.90, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Sandy", "Loam"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Border", "Foundation", "Slope", "Pool Area"],
    goals: ["Low Maintenance", "Spring Color", "Erosion Control", "Mass Planting"],
    companionPlants: ["agapanthus", "lavender", "japanese-maple", "photinia"],
    maintenanceLevel: "low",
    pruningNeeds: "Light shearing after bloom if needed; tolerates hard pruning",
    flowerColor: ["Pink", "White"],
    flowerSeason: ["Spring"],
    foliageColor: ["Dark Green", "Bronze-new growth"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Bronze new growth matures to dark green", interest: "Clusters of pink/white flowers" },
      summer: { foliage: "Dark green", interest: "Blue-black berries forming" },
      fall: { foliage: "Evergreen", interest: "Berries color up" },
      winter: { foliage: "Evergreen", interest: "Dependable green mass" }
    },
    why: "Bulletproof, year-round presence — one of the most reliable foundation plants",
    color: "#C48A9A",
    estimatedCostRange: [15, 55],
    usdaZones: ["7b", "8a", "8b", "9a", "9b", "10a", "10b"]
  },
  {
    id: "heavenly-bamboo",
    name: "Heavenly Bamboo",
    scientific: "Nandina domestica",
    family: "Berberidaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Upright multi-cane shrub with bamboo-like elegance",
    matureHeight: [3, 8],
    matureWidth: [3, 5],
    growthRate: "moderate",
    growthParam: { 1: 0.18, 5: 0.50, 10: 0.78, 20: 0.95, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade", "Full Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam", "Sandy"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Foundation", "Understory", "Border", "Screening"],
    goals: ["Four-Season Interest", "Low Maintenance", "Privacy", "Winter Interest"],
    companionPlants: ["japanese-maple", "agapanthus", "indian-hawthorn", "festuca"],
    maintenanceLevel: "low",
    pruningNeeds: "Remove oldest canes to ground every few years to rejuvenate",
    flowerColor: ["White"],
    flowerSeason: ["Spring", "Summer"],
    foliageColor: ["Red", "Green", "Bronze"],
    fallColor: "Scarlet",
    seasons: {
      spring: { foliage: "Soft pink-bronze new growth", interest: "White flower panicles" },
      summer: { foliage: "Green feathery fronds", interest: "Red berries forming" },
      fall: { foliage: "Orange-scarlet", interest: "Brilliant fall color\ + red berries" },
      winter: { foliage: "Scarlet-red (most cultivars)", interest: "Best winter color — red berries persist" }
    },
    why: "Year-round color chameleon — different every season with almost zero care",
    color: "#DC143C",
    estimatedCostRange: [20, 75],
    usdaZones: ["6a", "7a", "8a", "9a", "9b", "10a"]
  },
  {
    id: "salvia-greggii",
    name: "Autumn Sage",
    scientific: "Salvia greggii",
    family: "Lamiaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Compact airy sub-shrub",
    matureHeight: [2, 4],
    matureWidth: [2, 4],
    growthRate: "fast",
    growthParam: { 1: 0.30, 5: 0.70, 10: 0.90, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Sandy", "Rocky"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Border", "Dry Garden", "Pollinator Garden", "Pathway"],
    goals: ["Pollinator Habitat", "Hummingbirds", "Long Bloom", "Low Water"],
    companionPlants: ["lavender", "rosemary", "penstemon", "deer-grass"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut back by half in spring; remove spent flower spikes through season",
    flowerColor: ["Red", "Pink", "Coral", "White", "Purple"],
    flowerSeason: ["Spring", "Summer", "Fall"],
    foliageColor: ["Medium Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Small bright green leaves", interest: "First bloom flush" },
      summer: { foliage: "Green", interest: "Continuous bloom in heat" },
      fall: { foliage: "Green", interest: "Heavy fall bloom — best season" },
      winter: { foliage: "Semi-evergreen", interest: "Sporadic bloom in mild winters" }
    },
    why: "Hummingbirds fight over it from spring to frost — a non-stop red flower machine",
    color: "#E74C3C",
    estimatedCostRange: [10, 35],
    usdaZones: ["6b", "7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "penstemon",
    name: "Penstemon",
    scientific: "Penstemon spp.",
    family: "Plantaginaceae",
    type: "perennial",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Upright clumping perennial",
    matureHeight: [1, 4],
    matureWidth: [1, 2],
    growthRate: "fast",
    growthParam: { 1: 0.40, 5: 0.80, 10: 0.95, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Border", "Dry Garden", "Meadow", "Wildlife Habitat"],
    goals: ["Hummingbirds", "Pollinator Habitat", "Low Water", "Naturalistic"],
    companionPlants: ["salvia-greggii", "deer-grass", "blue-wild-rye", "yarrow"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut spent stalks; leave some for winter bird interest",
    flowerColor: ["Red", "Purple", "Pink", "Blue", "White"],
    flowerSeason: ["Spring", "Summer"],
    foliageColor: ["Green", "Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Low rosette of leaves", interest: "Tall flower spikes emerge — hummingbird feast" },
      summer: { foliage: "Green", interest: "Continued bloom in moderate climates" },
      fall: { foliage: "Green", interest: "Seed heads for birds" },
      winter: { foliage: "Semi-evergreen basal rosette", interest: "Structure" }
    },
    why: "California's hummingbird highway — native species support local ecosystems",
    color: "#9B59B6",
    estimatedCostRange: [8, 30],
    usdaZones: ["4a", "5a", "6a", "7a", "8a", "9a"]
  },
  {
    id: "yarrow",
    name: "Yarrow",
    scientific: "Achillea millefolium",
    family: "Asteraceae",
    type: "perennial",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Flat-topped spreading perennial",
    matureHeight: [1, 3],
    matureWidth: [1, 3],
    growthRate: "fast",
    growthParam: { 1: 0.45, 5: 0.85, 10: 0.97, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Meadow", "Slope", "Border", "Dry Garden"],
    goals: ["Pollinator Habitat", "Erosion Control", "Low Water", "Naturalistic"],
    companionPlants: ["penstemon", "blue-wild-rye", "deer-grass", "salvia-greggii"],
    maintenanceLevel: "none",
    pruningNeeds: "Cut to ground after bloom; divide every 3 years",
    flowerColor: ["White", "Yellow", "Pink", "Red"],
    flowerSeason: ["Spring", "Summer"],
    foliageColor: ["Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Ferny gray-green leaves", interest: "Flat-topped flower clusters begin" },
      summer: { foliage: "Gray-green", interest: "Peak bloom; masses of flat flower heads" },
      fall: { foliage: "Gray-green", interest: "Seed heads useful for birds; second bloom" },
      winter: { foliage: "Semi-evergreen to dormant", interest: "Structural seed heads" }
    },
    why: "Meadow magic that needs no water once established — butterflies and bees love it",
    color: "#F5CBA7",
    estimatedCostRange: [6, 20],
    usdaZones: ["3a", "4a", "5a", "6a", "7a", "8a", "9a"]
  },
  {
    id: "photinia",
    name: "Red Tip Photinia",
    scientific: "Photinia x fraseri",
    family: "Rosaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: false,
    fireResistant: false,
    form: "Upright large shrub or small tree",
    matureHeight: [10, 15],
    matureWidth: [8, 12],
    growthRate: "fast",
    growthParam: { 1: 0.15, 5: 0.50, 10: 0.80, 20: 0.97, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "moderate",
    soilTypes: ["Well-drained", "Loam", "Clay"],
    windTolerance: "moderate",
    heatTolerance: "moderate",
    situations: ["Screening", "Border", "Foundation", "Hedge"],
    goals: ["Privacy", "Spring Color", "Windbreak", "Fast Growing"],
    companionPlants: ["indian-hawthorn", "heavenly-bamboo", "agapanthus", "lavender"],
    maintenanceLevel: "moderate",
    pruningNeeds: "Prune new growth frequently to trigger red flushes; shape as hedge",
    flowerColor: ["White"],
    flowerSeason: ["Spring"],
    foliageColor: ["Green", "Bright Red-new growth"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Brilliant red new growth flushes", interest: "White flower clusters on older wood" },
      summer: { foliage: "Glossy green", interest: "Dense green screen" },
      fall: { foliage: "Green with some red tips", interest: "Continued screening" },
      winter: { foliage: "Evergreen", interest: "Red new growth may continue in mild winters" }
    },
    why: "Fastest privacy hedge with a brilliant red spring show — grows a foot a month",
    color: "#C0392B",
    estimatedCostRange: [20, 80],
    usdaZones: ["7a", "7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "magnolia-little-gem",
    name: "Little Gem Magnolia",
    scientific: "Magnolia grandiflora Little Gem",
    family: "Magnoliaceae",
    type: "tree",
    nativeCalifornia: false,
    deerResistant: false,
    fireResistant: false,
    form: "Narrow columnar evergreen tree",
    matureHeight: [15, 25],
    matureWidth: [7, 10],
    growthRate: "moderate",
    growthParam: { 1: 0.06, 5: 0.25, 10: 0.52, 20: 0.82, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "moderate",
    soilTypes: ["Well-drained", "Loam", "Clay"],
    windTolerance: "moderate",
    heatTolerance: "moderate",
    situations: ["Patio", "Driveway", "Formal Garden", "Entry"],
    goals: ["Statement Tree", "Fragrance", "Privacy", "Year-Round Structure"],
    companionPlants: ["agapanthus", "indian-hawthorn", "heavenly-bamboo", "lavender"],
    maintenanceLevel: "low",
    pruningNeeds: "Remove dead leaves from skirt annually; train for desired shape",
    flowerColor: ["White"],
    flowerSeason: ["Spring", "Summer", "Fall"],
    foliageColor: ["Dark Green", "Russet-Brown underside"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Glossy dark green, russet backs", interest: "First fragrant white blooms" },
      summer: { foliage: "Dark green", interest: "Peak bloom of large fragrant flowers" },
      fall: { foliage: "Evergreen", interest: "Continued bloom; red seed cones" },
      winter: { foliage: "Evergreen", interest: "Bold vertical form in winter garden" }
    },
    why: "Compact magnolia that blooms for months — incredible fragrance without the giant footprint",
    color: "#FFFFF0",
    estimatedCostRange: [80, 300],
    usdaZones: ["7a", "7b", "8a", "8b", "9a", "9b"]
  },
  {
    id: "agave",
    name: "Agave",
    scientific: "Agave americana",
    family: "Asparagaceae",
    type: "succulent",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: true,
    form: "Bold architectural rosette",
    matureHeight: [3, 8],
    matureWidth: [4, 10],
    growthRate: "slow",
    growthParam: { 1: 0.08, 5: 0.30, 10: 0.60, 20: 0.90, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Dry Garden", "Slope", "Poolside", "Entry"],
    goals: ["Statement Plant", "Architectural", "Low Water", "Deer Proof"],
    companionPlants: ["agave", "aloe-vera", "rosemary", "manzanita"],
    maintenanceLevel: "none",
    pruningNeeds: "Remove dead leaves from base; remove pups if wanted",
    flowerColor: ["Yellow"],
    flowerSeason: ["Summer"],
    foliageColor: ["Blue-Gray", "Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Bold blue-gray rosette", interest: "Architectural presence year-round" },
      summer: { foliage: "Blue-gray", interest: "Dramatic 20ft flower stalk (terminal bloom)" },
      fall: { foliage: "Evergreen", interest: "Pups form around dying parent" },
      winter: { foliage: "Evergreen", interest: "Sculptural form in dormant garden" }
    },
    why: "The ultimate fire-resistant architectural statement — thrives on total neglect",
    color: "#7F8C8D",
    estimatedCostRange: [25, 200],
    usdaZones: ["8a", "8b", "9a", "9b", "10a", "10b", "11a"]
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    scientific: "Aloe barbadensis",
    family: "Asphodelaceae",
    type: "succulent",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: true,
    form: "Upright succulent rosette",
    matureHeight: [1.5, 3],
    matureWidth: [2, 3],
    growthRate: "moderate",
    growthParam: { 1: 0.25, 5: 0.65, 10: 0.88, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Dry Garden", "Patio", "Slope", "Poolside"],
    goals: ["Low Water", "Edible/Medicinal", "Architectural", "Ground Cover"],
    companionPlants: ["agave", "rosemary", "salvia-greggii", "yarrow"],
    maintenanceLevel: "none",
    pruningNeeds: "Remove spent flower stalks; separate pups to control spread",
    flowerColor: ["Orange", "Yellow"],
    flowerSeason: ["Winter", "Spring"],
    foliageColor: ["Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Plump green-gray rosettes", interest: "Orange flower stalks emerge" },
      summer: { foliage: "Green-gray", interest: "Pups form; bold foliage mass" },
      fall: { foliage: "Evergreen", interest: "Foliage remains structural" },
      winter: { foliage: "Evergreen", interest: "Orange blooms in mild winters" }
    },
    why: "Nature's first-aid kit in a striking architectural form — zero water and zero fuss",
    color: "#A8B89A",
    estimatedCostRange: [5, 25],
    usdaZones: ["9a", "9b", "10a", "10b", "11a"]
  },
  {
    id: "festuca",
    name: "Blue Fescue",
    scientific: "Festuca glauca",
    family: "Poaceae",
    type: "grass",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Tight silvery blue mounding grass",
    matureHeight: [0.5, 1],
    matureWidth: [0.5, 1],
    growthRate: "moderate",
    growthParam: { 1: 0.35, 5: 0.75, 10: 0.95, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Sandy", "Rocky"],
    windTolerance: "moderate",
    heatTolerance: "moderate",
    situations: ["Border", "Pathway", "Slope", "Poolside"],
    goals: ["Edging", "Color Contrast", "Low Water", "Mass Planting"],
    companionPlants: ["lavender", "salvia-greggii", "agapanthus", "indian-hawthorn"],
    maintenanceLevel: "low",
    pruningNeeds: "Divide every 2-3 years; shear lightly in late winter",
    flowerColor: ["Tan"],
    flowerSeason: ["Summer"],
    foliageColor: ["Blue-Silver"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Bright silver-blue needles", interest: "Vivid blue color intensifies" },
      summer: { foliage: "Blue-silver", interest: "Tan flower spikes above blue mounds" },
      fall: { foliage: "Blue-gray", interest: "Color holds into cool weather" },
      winter: { foliage: "Blue-gray evergreen", interest: "Silver mounds dot the dormant garden" }
    },
    why: "A perfect blue anchor for borders — the blue foliage pairs with almost everything",
    color: "#7EC8E3",
    estimatedCostRange: [8, 25],
    usdaZones: ["4a", "5a", "6a", "7a", "8a", "9a"]
  },
  {
    id: "ceanothus",
    name: "California Lilac",
    scientific: "Ceanothus spp.",
    family: "Rhamnaceae",
    type: "shrub",
    nativeCalifornia: true,
    deerResistant: true,
    fireResistant: false,
    form: "Ground-hugging to large upright shrub",
    matureHeight: [1, 12],
    matureWidth: [4, 15],
    growthRate: "fast",
    growthParam: { 1: 0.20, 5: 0.60, 10: 0.85, 20: 0.97, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "none",
    soilTypes: ["Well-drained", "Sandy", "Rocky", "Poor"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Slope", "Dry Garden", "Wildlife Habitat", "Fire-Prone Area"],
    goals: ["Erosion Control", "Pollinator Habitat", "Low Water", "Spring Color"],
    companionPlants: ["manzanita", "toyon", "coast-live-oak", "coffeeberry"],
    maintenanceLevel: "none",
    pruningNeeds: "Light shearing after bloom only; do not cut into old wood",
    flowerColor: ["Blue", "Purple", "White", "Lavender"],
    flowerSeason: ["Spring"],
    foliageColor: ["Dark Green", "Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Dark glossy green", interest: "Spectacular blue bloom — best blue in California" },
      summer: { foliage: "Dark green", interest: "Nitrogen-fixing roots improve soil" },
      fall: { foliage: "Evergreen", interest: "Structure and bird habitat" },
      winter: { foliage: "Evergreen", interest: "Dense screening shrub" }
    },
    why: "The electric blue that defines California spring — impossible to miss in full bloom",
    color: "#4169E1",
    estimatedCostRange: [15, 75],
    usdaZones: ["7b", "8a", "8b", "9a", "9b", "10a"]
  },
  {
    id: "pineapple-guava",
    name: "Pineapple Guava",
    scientific: "Feijoa sellowiana",
    family: "Myrtaceae",
    type: "shrub",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Large rounded evergreen shrub or small tree",
    matureHeight: [10, 15],
    matureWidth: [10, 15],
    growthRate: "moderate",
    growthParam: { 1: 0.10, 5: 0.38, 10: 0.65, 20: 0.88, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Loam", "Clay", "Sandy"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Border", "Screening", "Edible Garden", "Large Property"],
    goals: ["Edible", "Privacy", "Pollinator Habitat", "Low Water"],
    companionPlants: ["olive-tree", "italian-cypress", "rosemary", "agave"],
    maintenanceLevel: "low",
    pruningNeeds: "Light shaping; harvest fruit in fall",
    flowerColor: ["Red", "White"],
    flowerSeason: ["Spring"],
    foliageColor: ["Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Silver-green", interest: "Stunning red and white orchid-like flowers (edible!)" },
      summer: { foliage: "Silver-green", interest: "Fruit developing" },
      fall: { foliage: "Evergreen", interest: "Guava fruit ripens — tropical-sweet flavor" },
      winter: { foliage: "Evergreen", interest: "Silver-green foliage; good screening" }
    },
    why: "Edible flowers AND edible fruit on a drought-tolerant screen — triple purpose plant",
    color: "#5D8A4E",
    estimatedCostRange: [25, 100],
    usdaZones: ["8a", "8b", "9a", "9b", "10a", "10b"]
  },
  {
    id: "kangaroo-paw",
    name: "Kangaroo Paw",
    scientific: "Anigozanthos flavidus",
    family: "Haemodoraceae",
    type: "perennial",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Upright clumping strap-leafed perennial",
    matureHeight: [2, 5],
    matureWidth: [2, 3],
    growthRate: "fast",
    growthParam: { 1: 0.35, 5: 0.75, 10: 0.92, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Sandy", "Rocky"],
    windTolerance: "moderate",
    heatTolerance: "high",
    situations: ["Border", "Dry Garden", "Poolside", "Patio"],
    goals: ["Hummingbirds", "Architectural", "Long Bloom", "Low Water"],
    companionPlants: ["agapanthus", "lavender", "salvia-greggii", "festuca"],
    maintenanceLevel: "low",
    pruningNeeds: "Cut spent flower stalks to base; divide every 3-4 years",
    flowerColor: ["Red", "Orange", "Yellow", "Pink", "Green"],
    flowerSeason: ["Spring", "Summer", "Fall"],
    foliageColor: ["Gray-Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Strap leaves emerge", interest: "First colorful tubular blooms" },
      summer: { foliage: "Gray-green straps", interest: "Peak bloom; hummingbird magnet" },
      fall: { foliage: "Green", interest: "Second bloom flush" },
      winter: { foliage: "Semi-evergreen", interest: "Structural foliage" }
    },
    why: "The most architecturally striking perennial for California heat — hummingbirds can't resist",
    color: "#E8550A",
    estimatedCostRange: [15, 50],
    usdaZones: ["9a", "9b", "10a", "10b"]
  },
  {
    id: "purple-coneflower",
    name: "Purple Coneflower",
    scientific: "Echinacea purpurea",
    family: "Asteraceae",
    type: "perennial",
    nativeCalifornia: false,
    deerResistant: true,
    fireResistant: false,
    form: "Upright clumping prairie perennial",
    matureHeight: [2, 4],
    matureWidth: [1.5, 2.5],
    growthRate: "moderate",
    growthParam: { 1: 0.30, 5: 0.70, 10: 0.90, 20: 1.0, 30: 1.0 },
    sunlight: ["Full Sun", "Partial Shade"],
    waterNeeds: "low",
    soilTypes: ["Well-drained", "Clay", "Loam", "Sandy"],
    windTolerance: "high",
    heatTolerance: "high",
    situations: ["Border", "Pollinator Garden", "Meadow", "Prairie Garden"],
    goals: ["Pollinator Habitat", "Wildlife", "Long Bloom", "Low Maintenance"],
    companionPlants: ["yarrow", "deer-grass", "salvia-greggii", "blue-wild-rye"],
    maintenanceLevel: "low",
    pruningNeeds: "Leave seed heads for birds in winter; cut to ground in late winter",
    flowerColor: ["Purple", "Pink", "White", "Orange"],
    flowerSeason: ["Summer", "Fall"],
    foliageColor: ["Dark Green"],
    fallColor: null,
    seasons: {
      spring: { foliage: "Low dark green basal rosette", interest: "Emerging flower buds" },
      summer: { foliage: "Dark green", interest: "Daisy flowers with orange cones for weeks" },
      fall: { foliage: "Darkening green", interest: "Continued bloom; cone seeds attract goldfinches" },
      winter: { foliage: "Dormant", interest: "Seed heads are beautiful and bird food" }
    },
    why: "The prairie perennial that does it all — bees, butterflies, goldfinches, and easy care",
    color: "#8E44AD",
    estimatedCostRange: [8, 30],
    usdaZones: ["3a", "4a", "5a", "6a", "7a", "8a", "9a"]
  }
];

// Helper: All unique situations
export const ALL_SITUATIONS = Array.from(
  new Set(PLANT_CATALOG.flatMap(p => p.situations))
).sort();

// Helper: All unique goals
export const ALL_GOALS = Array.from(
  new Set(PLANT_CATALOG.flatMap(p => p.goals))
).sort();
